### ISSUE TITLE
Extension Not Working

### ISSUE THREAD

**Issue by Mentalward** [mt-support/tribe-ext-events-control#4]
Hello, 
The TEC support/help desk told me to try to reach out to the developer about my issues with the extension. I am not sure if this is the best way, but I could really use the help.
--
I know that support for extensions is limited, but I am trying to use the "Events Control" extension. We currently have about 5+ sites with the TEC plugin and their events are going to be affected by COVID-19.

I attempted to install the extension on one of our sites as a test, but the fields are not appearing on the event. I have disabled all the plugins and reverted to a default theme, but nothing worked. I removed/disabled all the "additional fields" as well. I have updated all the plugins, themes, and WP 5.4 (in Dev for testing, but not prod). Nothing seems to work.

In the interim, I have created an "Event Category" called "Canceled" that triggers a "modal" with the notice about the cancelation  on the individual event page (https://www.fugecamps.com/event/carson-newman-university-june-29-july-3-2020-centrifuge/) and list view (https://www.fugecamps.com/find-a-camp/). However, it is not updating the LD-JSON/Structured Data/Schema, which is seems the extension would achieve.

I would love to know how I could get the extension to display OR how to update the JSON to include the https://schema.org/EventCancelled definition.

Thanks.
![fugedev wpengine com_wp-admin_post php_post=2735 action=edit--no_plugins](https://user-images.githubusercontent.com/3706963/78628381-9a0a2500-7859-11ea-981b-02044dab2964.png)
![fugedev wpengine com_wp-admin_post php_post=2735 action=edit](https://user-images.githubusercontent.com/3706963/78628388-9d051580-7859-11ea-9b47-cdf61c23deef.png)

**Comment by bordoni** [comment]
Hi @Mentalward,
It seems like you might not be seeing the Metabox on the sidebar of the events admin page due to using the legacy version of the views.

We are internally considering bringing compatibility for the legacy views for this extension, but if it's a possibility for you should also consider using the updated views that we released on version 5.0, keep in mind it's a major update and it might break customizations if you have those.

I will comment here later with an update with the team's decision on what I mentioned above.

Thanks a lot for the report.

**Comment by Mentalward** [comment]
@bordoni --
Thanks for the information. I know that we are having a similar issue with views with a new install. However, I am not sure how to convert or upgrade the views. 

What I have noticed is that the site I am referencing in this ticket uses:
/tribe-events/[dir or page]
and the most current one seems to be using
/tribe/events/[dir or page]

Is this what you mean? It looks like there is a discrepancy between TEC and TEC Pro. Is that correct?

Do you know if there is some documentation I could read?

**Comment by alorbach** [comment]
We ran into the same problem today and wasted 2 hours through the source code until we found out we had to perform "Events Settings->UPGRADE" to upgrade to the new VIEWS and get this plugin to work. 

I would recommend to add a notification to "The Events Calender" if an UPGRADE can be done, because I bet that almost nobody recognizes this (unless by accident). 

And I would recommend to through a warning when "tribe_events_views_v2_is_enabled" returns false in **Service_Provider.php ->register**
