### ISSUE TITLE
Template override not working

### ISSUE THREAD

**Issue by brianrc** [mt-support/tribe-ext-events-control#5]
It says at the top of the template files:
```
Override this template in your own theme by creating a file at:
 * [your-theme]/tribe/events-control/single/online-marker.php
```
However, it's not working. I add it to my child theme and it's not recognized. I've successfully done this with other Tribe plugins without issue.

**Comment by Mentalward** [comment]
I finally got it working in my environment and I'm running into the same issues.

I've tried the following:
[your-theme]/tribe/events-control/canceled-status.php
[your-theme]/tribe/events-control/single/canceled-status.php

[your-theme]/tribe/events-pro/v2/canceled-status.php
[your-theme]/tribe/events-pro/v2/single/canceled-status.php

[your-theme]/tribe/events/v2/canceled-status.php
[your-theme]/tribe/events/v2/single/canceled-status.php

[your-theme]/tribe-events/canceled-status.php
[your-theme]/tribe-events/single/canceled-status.php

[your-theme]/src/views/single/canceled-status.php
[your-theme]/src/views/canceled-status.php

None of those options worked. The only thing that worked was overriding the default templates in the plugin folder:
/wp-content/plugins/tribe-ext-events-control/src/views/single/canceled-status.php

Not the most ideal method, but I figured this isn't going to be a regularly updated extension.  I hope they fix the issue because I don't want to update the core files. I might opt to update only the "post-statuses.php" file with a new template call.

**Comment by bordoni** [comment]
I just merged the fix for the problem, if you head on over to the Extension page you will be able to download a version where it will look for the theme overwrite.
Correct paths are:
`[your-theme]/tribe/events-control/canceled-status.php`
`[your-theme]/tribe/events-control/single/canceled-status.php`
